---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: send-message
spec:
  templates:
    - name: send-message
      inputs:
        parameters:
          - name: THOTH_MESSAGING_TOPIC_NAME
          - name: THOTH_MESSAGING_CREATE_IF_NOT_EXISTS
          - name: THOTH_MESSAGING_MESSAGE_CONTENTS
          - name: THOTH_MESSAGING_PARTITIONS
            value: ""  # this is the same as having unset so it will use the default
          - name: THOTH_MESSAGING_REPLICATION
            value: ""
          - name: THOTH_MESSAGING_TOPIC_RETENTION_TIME
            value: ""
      container:
        name: send-message
        image: messaging
        env:
          - name: THOTH_MESSAGING_TOPIC_NAME
            value: "{{inputs.parameters.THOTH_MESSAGING_TOPIC_NAME}}"
          - name: THOTH_MESSAGING_CREATE_IF_NOT_EXISTS
            value: "{{inputs.parameters.THOTH_MESSAGING_CREATE_IF_NOT_EXISTS}}"
          - name: THOTH_MESSAGING_MESSAGE_CONTENTS
            value: "{{inputs.parameters.THOTH_MESSAGING_MESSAGE_CONTENTS}}"
          - name: THOTH_MESSAGING_PARTITIONS
            value: "{{inputs.parameters.THOTH_MESSAGING_PARTITIONS}}"
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: KAFKA_BOOTSTRAP_SERVERS
                key: kafka-bootstrap-servers
          - name: KAFKA_CAFILE
            value: "/mnt/kafka-secrets/kafka_ca.crt"
        volumeMounts:
          - name: secrets
            mountPath: /mnt/kafka-secrets
      ##########################################################################
      # NOTE: when using this in your workflow be sure to supply secret volume
      # volumes:
      #   - name: kafka-secrets
      #     secret:
      #       secretName: "kafka"
      #       items:
      #         - key: kafka_ca.crt
      #           path: kafka_ca.crt
      ###########################################################################
