apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: init-job
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/init-job:v0.7.0
    importPolicy: {}
    referencePolicy:
      type: Local
