---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sefkhet-abwy
data:
  subdomain: sefkhet-abwy
  webhook-callback-url: "http://sefkhet-abwy-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com"
