apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - configmap.yaml
  - imagestreamtag.yaml
patchesJson6902:
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: kebechet
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: kebechet-run-url
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
