---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: argocli
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workflow-controller
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: argoexec
spec:
  lookupPolicy:
    local: true
