---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-thoth-ubi8-py36
spec:
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "1"
      memory: 768Mi
  output:
    to:
      kind: ImageStreamTag
      name: s2i-thoth-ubi8-py36:latest
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/thoth-station/s2i-thoth"
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: "ubi8-py36/Dockerfile"
      noCache: true
    env:
      - name: ENABLE_PIPENV
        value: "1"
      - name: UPGRADE_PIP_TO_LATEST
        value: ""
  triggers:
    - imageChange: {}
      type: ImageChange
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: amun-inspect-hwinfo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: amun-inspect-hwinfo:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/thoth-station/amun-hwinfo
      ref: master
    type: Git
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-thoth-ubi8-py36:latest
      env:
        - name: ENABLE_PIPENV
          value: "1"
        - name: UPGRADE_PIP_TO_LATEST
          value: "0"
        - name: "THOTH_DRY_RUN"
          value: "1"
        - name: "THOTH_ADVISE"
          value: "0"
        - name: "THAMOS_VERBOSE"
          value: "1"
        - name: "THAMOS_DEBUG"
          value: "0"
        - name: "THAMOS_CONFIG_TEMPLATE"
          value: ".thoth.yaml"
        - name: "THAMOS_CONFIG_EXPAND_ENV"
          value: "1"
  triggers:
    - type: "ConfigChange"
