---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amun-api
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/amun-api:v0.9.2
    importPolicy: {}
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amun-inspect-hwinfo
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/amun-inspect-hwinfo:v0.1.2
    importPolicy: {}
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kubectl
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/kubectl:latest
    importPolicy: {}
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workflow-helpers
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/workflow-helpers:latest
    importPolicy: {}
    referencePolicy:
      type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/thoth-station/messaging:latest
