---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hook
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210204-de2fa22b93
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/hook:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/hook:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sinker
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210204-de2fa22b93
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/sinker:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/sinker:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: deck
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210204-de2fa22b93
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/deck:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/deck:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: horologium
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/horologium:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/horologium:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tide
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210204-de2fa22b93
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/tide:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/tide:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: status-reconciler
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/status-reconciler:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/status-reconciler:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: crier
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/crier:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/crier:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: needs-rebase
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/needs-rebase:v20210204-de2fa22b93
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/needs-rebase:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: label-sync
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210127-5fd357428d
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/label_sync:v20210127-5fd357428d
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/label_sync:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pipeline
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: ImageStreamTag
        name: v20210211-72696ce111
    - annotations: null
      name: v20210201-6494714d87
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/pipeline:v20210201-6494714d87
      importPolicy: {}
      referencePolicy:
        type: Local
    - annotations: null
      name: v20210211-72696ce111
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/pipeline:v20210211-72696ce111
      importPolicy: {}
      referencePolicy:
        type: Local
